version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

jobs:
  run-ai-summarizer:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Prepare Error Log File
          command: |
            echo "📝 Preparing error log file..."
            cp sample_error_log.txt error_log.txt

      - run:
          name: Run AI Summarizer Script
          command: |
            echo "🤖 Running AI summarizer..."
            ./run_summarizer.sh

      - run:
          name: Display AI Summary
          command: |
            echo "===== 🧠 AI-Generated Summary ====="
            cat error_summary.md
            echo "==================================="

workflows:
  run-ai-agent:
    jobs:
      - run-ai-summarizer

